In [2]:
import numpy as np

In [3]:
from numpy import genfromtxt
df=genfromtxt("DS1_C4_S2_Admission_Predict_Practice.csv", delimiter=',',skip_header=1)
print(df)
cols={0:'SerialNo',1:'GRE',2:'TOEFEL',3:'Univ Rating',4:'SOP',5:'LOR',6:'CGPA',7:'Research',8:'Chace of Adimission'}

[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  3.   316.   104.   ...   8.     1.     0.72]
 ...
 [398.   330.   116.   ...   9.45   1.     0.91]
 [399.   312.   103.   ...   8.78   0.     0.67]
 [400.   333.   117.   ...   9.66   1.     0.95]]


In [4]:
# Task 1
ind=np.where(df[:,1]>320)
a=np.count_nonzero(ind)
print(a)


162


In [5]:
# Task 2
ind=np.where(df[:,2]>110)
print("The admission possibilities of students with TOEFEL score greater than 110 are :", df[ind,8])

The admission possibilities of students with TOEFEL score greater than 110 are : [[0.92 0.9  0.84 0.78 0.7  0.94 0.95 0.97 0.94 0.91 0.9  0.94 0.87 0.91
  0.86 0.89 0.78 0.78 0.72 0.52 0.55 0.61 0.78 0.94 0.96 0.93 0.72 0.74
  0.96 0.92 0.94 0.86 0.9  0.79 0.74 0.87 0.91 0.93 0.94 0.94 0.85 0.78
  0.84 0.92 0.96 0.79 0.89 0.8  0.9  0.92 0.97 0.8  0.81 0.83 0.96 0.93
  0.94 0.86 0.81 0.89 0.89 0.87 0.85 0.9  0.89 0.93 0.93 0.88 0.9  0.86
  0.94 0.97 0.97 0.95 0.96 0.94 0.93 0.91 0.76 0.71 0.82 0.91 0.88 0.85
  0.86 0.7  0.76 0.77 0.93 0.85 0.9  0.7  0.83 0.89 0.8  0.94 0.93 0.92
  0.89 0.86 0.9  0.71 0.8  0.79 0.8  0.81 0.8  0.8  0.83 0.94 0.93 0.91
  0.86 0.95 0.96 0.96 0.84 0.89 0.91 0.95]]


In [6]:
# Task 3
sort_gre=np.sort(df[:,1])[::-1]
print(sort_gre[0:11])
ind_gre=np.where(df[:,1]>=339)
print("The list of top 11 GRE scorers are:", df[ind_gre])

sort_toefel=np.sort(df[:,2])[::-1]
print(sort_toefel[0:11])
ind_toefel=np.where(df[:,2]==120)
print("The list of top 8 TOEFEL scorers are :",df[ind_toefel])


[340. 340. 340. 340. 340. 340. 340. 340. 339. 339. 339.]
The list of top 11 GRE scorers are: [[ 26.   340.   120.     5.     4.5    4.5    9.6    1.     0.94]
 [ 34.   340.   114.     5.     4.     4.     9.6    1.     0.9 ]
 [ 48.   339.   119.     5.     4.5    4.     9.7    0.     0.89]
 [ 82.   340.   120.     4.     5.     5.     9.5    1.     0.96]
 [ 85.   340.   115.     5.     4.5    4.5    9.45   1.     0.94]
 [131.   339.   114.     5.     4.     4.5    9.76   1.     0.96]
 [144.   340.   120.     4.     4.5    4.     9.92   1.     0.97]
 [149.   339.   116.     4.     4.     3.5    9.8    1.     0.96]
 [203.   340.   120.     5.     4.5    4.5    9.91   1.     0.97]
 [285.   340.   112.     4.     5.     4.5    9.66   1.     0.94]
 [385.   340.   113.     4.     5.     5.     9.74   1.     0.96]]
[120. 120. 120. 120. 120. 120. 120. 120. 119. 119. 119.]
The list of top 8 TOEFEL scorers are : [[ 26.   340.   120.     5.     4.5    4.5    9.6    1.     0.94]
 [ 82.   340.   12

In [7]:
# Task 4
ind=np.where(((df[:,1]>299)&(df[:,1]<306))&(df[:,4]==3.5)&(df[:,7]==1))
df1=df[ind]
print("The serial number and toefel scores of these students are: ", df1[0:3:2].T)



The serial number and toefel scores of these students are:  [[113.   358.  ]
 [301.   301.  ]
 [107.   104.  ]
 [  3.     2.  ]
 [  3.5    3.5 ]
 [  3.5    3.5 ]
 [  8.34   7.89]
 [  1.     1.  ]
 [  0.62   0.68]]


In [8]:
# Task 5
scholarship=np.random.randint(5000,10000,size=(400,1))
df=np.append(df,scholarship,axis=1)
print(df)
sch=np.where(df[:,9]>9000)
a=np.count_nonzero(sch)
print("Total Students with scholarship more than 9000 are :", a)

[[1.000e+00 3.370e+02 1.180e+02 ... 1.000e+00 9.200e-01 8.235e+03]
 [2.000e+00 3.240e+02 1.070e+02 ... 1.000e+00 7.600e-01 7.507e+03]
 [3.000e+00 3.160e+02 1.040e+02 ... 1.000e+00 7.200e-01 7.386e+03]
 ...
 [3.980e+02 3.300e+02 1.160e+02 ... 1.000e+00 9.100e-01 7.705e+03]
 [3.990e+02 3.120e+02 1.030e+02 ... 0.000e+00 6.700e-01 5.779e+03]
 [4.000e+02 3.330e+02 1.170e+02 ... 1.000e+00 9.500e-01 8.770e+03]]
Total Students with scholarship more than 9000 are : 74


In [14]:
# Task 6
print("The SOP and LOR scores of students with scholarship more than $9000\n",df[:,[4,5]])





The SOP and LOR scores of students with scholarship more than $9000
 [[4.5 4.5]
 [4.  4.5]
 [3.  3.5]
 [3.5 2.5]
 [2.  3. ]
 [4.5 3. ]
 [3.  4. ]
 [3.  4. ]
 [2.  1.5]
 [3.5 3. ]
 [3.5 4. ]
 [4.  4.5]
 [4.  4.5]
 [4.  3. ]
 [3.5 2. ]
 [3.5 2.5]
 [4.  3. ]
 [4.  3. ]
 [4.  3. ]
 [3.5 3. ]
 [3.  2. ]
 [3.  2. ]
 [5.  5. ]
 [5.  4.5]
 [4.  3.5]
 [4.5 4.5]
 [4.5 3.5]
 [1.5 2.5]
 [2.  2. ]
 [1.5 2. ]
 [3.  3. ]
 [4.  4. ]
 [3.  4.5]
 [4.  4. ]
 [4.  5. ]
 [5.  5. ]
 [4.  4. ]
 [1.  2. ]
 [3.  1.5]
 [4.  3.5]
 [3.5 3. ]
 [2.5 2.5]
 [2.5 2. ]
 [4.5 4. ]
 [4.5 4. ]
 [5.  4. ]
 [4.  5. ]
 [4.5 4. ]
 [3.5 5. ]
 [3.  4. ]
 [2.5 4.5]
 [1.5 3.5]
 [4.  3. ]
 [4.  2.5]
 [3.  3.5]
 [3.  3. ]
 [2.  3. ]
 [4.  2. ]
 [3.  2. ]
 [2.  2. ]
 [3.  3. ]
 [4.  3. ]
 [3.  3. ]
 [4.  3. ]
 [3.  3.5]
 [3.5 3.5]
 [3.  3. ]
 [3.5 3.5]
 [3.5 4. ]
 [4.5 4. ]
 [5.  5. ]
 [5.  5. ]
 [5.  5. ]
 [4.5 4. ]
 [3.  5. ]
 [2.  4. ]
 [3.  3. ]
 [3.  2. ]
 [3.  2. ]
 [1.5 2. ]
 [2.  3. ]
 [5.  5. ]
 [5.  4.5]
 [4.  4.5]
 [4.5 4

In [16]:
# Task 7
sch_1=np.where((df[:,1]>315)&(df[:,2]>115)&(df[:,7]==1))
print("Serial numbers of students eligible for additional scholarship of $1000 are,\n",df[sch_1][:,0])
print("Number of students eligible for additional scholarship =",df[sch_1].shape[0])


Serial numbers of students eligible for additional scholarship of $1000 are,
 [  1.  23.  24.  25.  26.  33.  53.  71.  82.  98.  99. 108. 109. 121.
 122. 130. 139. 142. 144. 149. 152. 172. 177. 188. 194. 203. 204. 213.
 214. 215. 216. 260. 286. 287. 326. 338. 362. 373. 386. 398. 400.]
Number of students eligible for additional scholarship = 41


In [34]:
ad=df[sch_1]=df[sch_1]+1000


In [39]:
sch_updated=np.concatenate((df,ad),axis=1)
print("Updated Scholarship data",sch_updated[sch_1][:,-1])

Updated Scholarship data [11235. 10119.  9480. 11149. 12172.  9136.  9755.  9342.  9268.  9458.
 11829. 10087.  8132. 11210.  9323. 10285.  9377. 10003. 11139. 10887.
  8970.  9059. 10932. 11792.  9672. 11322. 10521.  9976. 11170.  9974.
 11744. 12726. 12609.  9945. 12223. 12053. 11736. 12747. 10131. 10705.
 11770.]
