In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
#Task 1

In [3]:
tf.strings.join(['5988','Aditya','AK@gmail.com','123457856','Bangalore','Male','03/08/1999'],separator=" ")

<tf.Tensor: shape=(), dtype=string, numpy=b'5988 Aditya AK@gmail.com 123457856 Bangalore Male 03/08/1999'>

In [4]:
#Task 2

In [5]:
matrix =tf.constant([['Indigo','violet','programmer'], ['computer','training', 'kitchen'], ['array', 'instagram', 'bluetooth']])

In [6]:
start_pos = tf.constant(np.random.randint(1,5,9).reshape(3,3))
num_of_chars = tf.constant(np.random.randint(1,5,9).reshape(3,3))
tf.strings.substr(matrix,start_pos,num_of_chars )

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'igo', b'l', b'gram'],
       [b'u', b'inin', b'c'],
       [b'r', b'agr', b'toot']], dtype=object)>

In [7]:
#Task 3

In [8]:
product_price=tf.constant(1895.12)

In [9]:
print(product_price)

tf.Tensor(1895.12, shape=(), dtype=float32)


In [10]:
#data type float16
product_price=tf.constant(1895.2,tf.float16)

In [11]:
print (product_price)

tf.Tensor(1895.0, shape=(), dtype=float16)


In [12]:
#Task 4

In [13]:
marks=tf.constant(np.random.randint(1,100,15).reshape(5,3))
marks=tf.cast(marks,tf.int16)
marks1=tf.Variable(marks)
print("Values of matrix before updating:", marks1)
upd_marks=np.random.randint(1,100,15).reshape(5,3)
marks1.assign(upd_marks)
print("Values of matrix after updating:", marks1)


Values of matrix before updating: <tf.Variable 'Variable:0' shape=(5, 3) dtype=int16, numpy=
array([[99, 59, 28],
       [49, 59, 75],
       [ 4, 29, 80],
       [65,  6, 17],
       [56, 12, 72]], dtype=int16)>
Values of matrix after updating: <tf.Variable 'Variable:0' shape=(5, 3) dtype=int16, numpy=
array([[74, 49, 99],
       [80, 23, 53],
       [41, 55,  3],
       [54, 49, 16],
       [97, 12, 75]], dtype=int16)>


In [14]:
#Task 5

In [15]:
#Task 6

In [16]:
customer = {'Name':['Aditya', 'Sonya', 'Varun'], 'age':[23, 21, 35],  'gender':['F', 'M', 'F']}
print(customer)

{'Name': ['Aditya', 'Sonya', 'Varun'], 'age': [23, 21, 35], 'gender': ['F', 'M', 'F']}


In [17]:
t_currency = {'USA':'Dollar', 'China':'Yuan','UK':'Pound'}
print(t_currency)

{'USA': 'Dollar', 'China': 'Yuan', 'UK': 'Pound'}


In [18]:
t_keys = tf.convert_to_tensor(list(t_currency.keys()))
print(t_keys)
t_values = tf.convert_to_tensor(list(t_currency.values()))
print(t_values)

tf.Tensor([b'USA' b'China' b'UK'], shape=(3,), dtype=string)
tf.Tensor([b'Dollar' b'Yuan' b'Pound'], shape=(3,), dtype=string)


In [19]:
#Task 7

In [20]:
unit=tf.constant([10,15,20,25])
unit

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 15, 20, 25], dtype=int32)>

In [21]:
unit_price=tf.constant([75,45,100,200])
unit_price

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 75,  45, 100, 200], dtype=int32)>

In [22]:
grand_total=sum(unit*unit_price)
print("Grand total of all the prices",grand_total)

Grand total of all the prices tf.Tensor(8425, shape=(), dtype=int32)
